In [1]:
from QualtricsAPI.Setup import Credentials
from QualtricsAPI.XM import XMDirectory
from QualtricsAPI.XM import MailingList
from QualtricsAPI.Survey import Responses
import shutil
import os
import requests
import zipfile
import json
import io
import pandas as pd
import re
import openpyxl
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.patches import Rectangle
from reportlab.lib.pagesizes import letter, landscape, A4, A3
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, PageBreak, Paragraph, Spacer, Image, HRFlowable
from reportlab.lib import colors
from matplotlib.backends.backend_pdf import PdfPages
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import Paragraph, Spacer, KeepTogether, KeepInFrame 
from reportlab.graphics.shapes import Drawing, Rect, String
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from variableUtils import *
from Utils import *
pd.set_option('display.max_columns', None)

(841.68, 1190.8799999999999)

In [2]:
apiToken = 'HbeDqDB2kRbueZdGg9EhjMt2DDElVuvBxTR7HKhU'
dataCenter = 'syd1'
#Get Survey Responses (Updated)
kwargs = {"token": apiToken, "data_center": dataCenter}
Credentials().qualtrics_api_credentials(**kwargs)

surveyDict = {
              'Oral Med': 'SV_cON7eSWP0BaEfxs',
              'Paeds': 'SV_e9VZvANQN30lKzI',
              'Ortho': 'SV_5ySXHQWpXGSbucK',
              'Perio': 'SV_7VBSuXV72s6hHvg',
            #   'Endo': 'SV_e2mbfiJzLDNZNpY',
              'Endo': 'SV_9Tam9mLwlSIW4NU',
            #   'Endo': 'SV_bIpzp6dE2Chxvls',
              'Pros': 'SV_43eYaPYStmWegvA'
}


dfDict = {}
for key, value in surveyDict.items():
    df = Responses().get_survey_responses(survey=value, verify=None, useLabels=True)
    # drop rows 0 and 1
    df.drop([0, 1], inplace=True)
    dfDict[key] = df
    # display(df.head(10))

In [3]:
dfOmed = dfDict['Oral Med']
dfPaeds = dfDict['Paeds']
dfOrtho = dfDict['Ortho']
dfPerio = dfDict['Perio']
dfEndo = dfDict['Endo']
dfPros = dfDict['Pros']
print(len(dfOrtho))
display(dfEndo.tail(5))
# dfEndo.to_excel('DCD/Endo.xlsx', index=False)
# display(dfPros.tail(5))

241

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Date,Student Name,Semester,Site_4,Site_5,Staff,Professionalism,Dialogue,Assessment,Diff Diagnosis,Treatment Plan,Intervention,Evaluation,Readiness to practic,Q11,Q12,Q22,Q23_Id,Q23_Name,Q23_Size,Q23_Type,gname,fname,uomid,Marks
36,2026-09-03 06:50:45,2026-09-03 06:52:12,IP Address,146.75.209.5,100,87,True,2026-09-03 06:52:13,R_42JLW5T5JTb59sO,NaN,NaN,NaN,NaN,-33.8672,151.1997,qr,EN,3 Sep 2026,Adam Saker,2,Royal Dental Hospital Melbourne RDHM,NaN,NaN,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Surpassing expectations at this point in educa...,Good patient management,None,Exceeds expected level of performance consider...,F_2cnexkti6znOd6V,signature.png,4159,image/png,NaN,NaN,NaN,NaN
37,2026-09-07 06:07:31,2026-09-07 06:08:49,IP Address,128.250.0.1,100,78,True,2026-09-07 06:08:50,R_92Aky7W4TAaPu0O,NaN,NaN,NaN,NaN,-37.8159,144.9669,qr,EN,7 Sep 2026,Adam Saker,2,Royal Dental Hospital Melbourne RDHM,NaN,NaN,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Surpassing expectations at this point in educa...,Patient management \nTroubleshooting,Need to improve efficiency,Exceeds expected level of performance consider...,F_ONboYhkWxG49Pwt,signature.png,4408,image/png,NaN,NaN,NaN,NaN
38,2026-09-07 06:09:00,2026-09-07 06:10:32,IP Address,128.250.0.1,100,91,True,2026-09-07 06:10:33,R_4kgM8rMrwZUkrHG,NaN,NaN,NaN,NaN,-37.8159,144.9669,qr,EN,7 Sep 2026,Ethan Zappala,2,Royal Dental Hospital Melbourne RDHM,NaN,NaN,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Progressing appropriately,"Good, very methodical",Need to build more confidence,Exceeds expected level of performance consider...,F_3h3ljTCHQicRpRd,signature.png,4585,image/png,NaN,NaN,NaN,NaN
39,2026-09-07 06:10:48,2026-09-07 06:12:10,IP Address,128.250.0.1,100,82,True,2026-09-07 06:12:11,R_4iX74RlvlxI8Evr,NaN,NaN,NaN,NaN,-37.8159,144.9669,qr,EN,7 Sep 2026,Yu Chen Guan,2,Royal Dental Hospital Melbourne RDHM,NaN,NaN,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Progressing appropriately,Good patient management,Improve on radiograph skills,Exceeds expected level of performance consider...,F_1rCZ16f73pByCtS,signature.png,4524,image/png,NaN,NaN,NaN,NaN
40,2026-09-07 06:12:32,2026-09-07 06:14:04,IP Address,128.250.0.1,100,91,True,2026-09-07 06:14:05,R_9MSX1pE0FO7F1hj,NaN,NaN,NaN,NaN,-37.8159,144.9669,qr,EN,7 Sep 2026,Andrew Chan,2,Royal Dental Hospital Melbourne RDHM,NaN,NaN,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Meets expectations at this point in education,Progressing appropriately,Good case management,Build more clinical confidence,Exceeds expected level of performance consider...,F_2zCKmax5JSGt2Wl,signature.png,4800,image/png,NaN,NaN,NaN,NaN

In [4]:
rubricColumns = ["Professionalism", "Dialogue", "Assessment", "Diff Diagnosis", "Treatment Plan", "Intervention", "Evaluation"]
readinessCol = 'Readiness to practic' # Level 1 etc.
colFinished = 'Finished' # True/False
siteCols = ["Site_4", "Site_5", "Site_10", "Site_11", "Site_12"]
sites = ["Royal Dental Hospital Melbourne RDHM", "Melbourne Dental Clinic", "RCH", "On call at RCH", "Shadowing at RCH"]

grades = ['Meets expectations at this point in education', "Does not meet expectations at this point in education", "Not applicable"]
strengths = 'Q11' #comments
weaknesses = 'Q12' #comments
# some rubrics have names instead of levels in readiness to practice, so we will need to map them to levels
rubricScoreDict = {
 'Critically behind expectations at this point in education': 'Level 1',
    'Slightly behind expectations at this point in education': 'Level 2',
    'Progressing appropriately': 'Level 3',
    'Surpassing expectations at this point in education': 'Level 4', 
}
dfEndo[readinessCol] = dfEndo[readinessCol].replace(rubricScoreDict)

def getRubricCounts(studentDf, columnName):
    valueSeries = studentDf[columnName].fillna("").astype(str).str.strip()

    belowCount = (valueSeries == "Does not meet expectations at this point in education").sum()
    meetsCount = (valueSeries == "Meets expectations at this point in education").sum()
    naCount = (valueSeries == "Not applicable").sum()

    totalCount = belowCount + meetsCount + naCount

    return {
        "below": int(belowCount),
        "meets": int(meetsCount),
        "na": int(naCount),
        "total": int(totalCount)
    }

def createRubricBar(columnName, counts, barWidth=540, barHeight=24):
    drawingHeight = 58
    drawing = Drawing(barWidth, drawingHeight)
    belowColor = colors.HexColor("#094183")
    meetsColor = colors.HexColor("#4597ad")
    naColor = colors.HexColor("#6f6f6f")
    borderColor = colors.HexColor("#0f0f0f")
    emptyColor = colors.white
    maxCells = counts["total"] if counts["total"] > 0 else 1

    labelFontSize = 9
    titleFontSize = 11

    if maxCells is None:
        maxCells = counts["total"] if counts["total"] > 0 else 1

    drawingHeight = 60
    drawing = Drawing(barWidth, drawingHeight)

    drawing.add(String(0, 46, columnName, fontName="Helvetica-Bold", fontSize=titleFontSize))
    # drawing.add(String(0, 28, "Student self-evaluation", fontName="Helvetica", fontSize=10))
    drawing.add(String(barWidth/6, 8 + barHeight + 10, "Below Expectation", fontName="Helvetica-Bold", fontSize=labelFontSize))
    # add a small rectangle as a legend for below expectation
    drawing.add(Rect(barWidth/6 - 12, 8 + barHeight + 6, 10, 10, fillColor=belowColor, strokeColor=borderColor, strokeWidth=0.8))
    drawing.add(String(barWidth/2, 8 + barHeight + 10, "Meets Expectation", fontName="Helvetica-Bold", fontSize=labelFontSize))
    # add a small rectangle as a legend for meets expectation
    drawing.add(Rect(barWidth/2 - 12, 8 + barHeight + 6, 10, 10, fillColor=meetsColor, strokeColor=borderColor, strokeWidth=0.8))
    drawing.add(String(5*barWidth/6, 8 + barHeight + 10, "Not Applicable", fontName="Helvetica-Bold", fontSize=labelFontSize))
    # add a small rectangle as a legend for not applicable
    drawing.add(Rect(5*barWidth/6 - 12, 8 + barHeight + 6, 10, 10, fillColor=naColor, strokeColor=borderColor, strokeWidth=0.8))

    barY = 8
    cellWidth = barWidth / maxCells

    cellColors = ([belowColor] * counts["below"] + [meetsColor] * counts["meets"] + [naColor] * counts["na"])

    if len(cellColors) < maxCells:
        cellColors += [emptyColor] * (maxCells - len(cellColors))

    for index in range(maxCells):
        xPos = index * cellWidth
        drawing.add(Rect(xPos, barY, cellWidth, barHeight, fillColor=cellColors[index], strokeColor=borderColor, strokeWidth=0.8))

    drawing.add(Rect(0, barY, barWidth, barHeight, fillColor=None, strokeColor=borderColor, strokeWidth=1))

    return drawing

def createReadinessLegend():
    drawing = Drawing(520, 20)

    items = [
        ("Level 1", colors.HexColor("#c0392b")), ("Level 2", colors.HexColor("#e67e22")), 
        ("Level 3", colors.HexColor("#56a3b9")), ("Level 4", colors.HexColor("#4c8f5a")),
    ]

    x = 0
    for label, color in items:
        drawing.add(Rect(x, 4, 12, 12, fillColor=color, strokeColor=colors.black))
        drawing.add(String(x + 18, 6, label, fontName="Helvetica", fontSize=9))
        x += 120

    return drawing

def createReadinessBar(studentDf, readinessCol, barWidth=520, barHeight=22):

    levelSeries = (
        studentDf[readinessCol]
        .astype(str)
        .str.extract(r"Level\s*(\d+)", expand=False)
        .dropna()
        .astype(int)
    )

    counts = levelSeries.value_counts().to_dict()

    maxLevel = 4
    maxCells = max(len(levelSeries), 1)

    levelColors = {
        1: colors.HexColor("#c0392b"),
        2: colors.HexColor("#e67e22"),
        3: colors.HexColor("#56a3b9"),
        4: colors.HexColor("#4c8f5a")
    }

    borderColor = colors.HexColor("#666666")

    drawing = Drawing(barWidth, 60)

    drawing.add(String(0, 42, "Readiness to Practice", fontName="Helvetica-Bold", fontSize=14))

    cellWidth = barWidth / maxCells
    barY = 8

    levelCells = []

    for level in range(1, maxLevel + 1):
        levelCells += [level] * counts.get(level, 0)

    if len(levelCells) < maxCells:
        levelCells += [0] * (maxCells - len(levelCells))

    for i, level in enumerate(levelCells):

        x = i * cellWidth

        fill = levelColors.get(level, colors.white)

        drawing.add(Rect(x, barY, cellWidth, barHeight, fillColor=fill, strokeColor=borderColor, strokeWidth=0.8))

    drawing.add(Rect(0, barY, barWidth, barHeight, fillColor=None, strokeColor=borderColor, strokeWidth=1))

    return drawing

def createStudentReport(df, studentname, folder, cohortname):
    subheadingStyleL.fontSize = 18
    doc = SimpleDocTemplate(f"{folder}/{studentname}.pdf", pagesize=pageSize, rightMargin=rightMargin, leftMargin=leftMargin, topMargin=topMargin, bottomMargin=bottomMargin)
    elements = []
    studentDf = df[df['Student Name'] == studentname]
    # display(studentDf)
    if studentDf.empty:
        print(f"No data found for student: {studentname}")
        return None
    elements.append(Spacer(1, 72))

    # add number of finshed forms
    elements.append(Paragraph(f"Number of feedback forms: {len(studentDf)}", subheadingStyleL))

    # add clinical placements
    elements.append(Paragraph("Clinical placements", subheadingStyleL))
    allSites = studentDf['Sites Attended'].str.split(', ').explode().unique()
    allSites = [site for site in allSites if pd.notna(site)]
    allSites = list(set(allSites))
    siteRows = []
    for site in sites:
        marker = "[X]" if site in allSites else "[ ]"
        siteRows.append([Paragraph(marker, subsubheadingStyleL), Paragraph(site, subsubheadingStyleL)])
    siteTable = Table(siteRows, colWidths=[0.3*inch, 5*inch], hAlign='LEFT')
    siteTable.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    elements.append(siteTable)
    elements.append(Spacer(1, 36))

    # add rubric bars
    elements.append(Paragraph("Feedback Domains", subheadingStyleL))
    elements.append(Spacer(1, 12))
    for rubricCol in rubricColumns:
        if rubricCol in studentDf.columns:
            counts = getRubricCounts(studentDf, rubricCol)
            rubricBar = createRubricBar(rubricCol, counts, barWidth = pageSize[0] - leftMargin - rightMargin - 2*inch, barHeight=18)
            elements.append(rubricBar)
            elements.append(Spacer(1, 12))

    # add readiness bar
    elements.append(HRFlowable(width="100%", thickness=1, color=uniColor))
    if readinessCol in studentDf.columns:
        readinessBar = createReadinessBar(studentDf, readinessCol, barWidth = pageSize[0] - leftMargin - rightMargin - 2*inch, barHeight=18)
        elements.append(Spacer(1, 12))
        elements.append(readinessBar)
        readinesslegend = createReadinessLegend()
        elements.append(Spacer(1, 6))
        elements.append(readinesslegend)

    # add comments   
    elements.append(PageBreak())
    elements.append(Paragraph("Strengths", subheadingStyleL))
    strengthDf = studentDf[['Date', strengths]]
    strengthDf = strengthDf.dropna(subset=[strengths])
    strengthDf.columns = ['Date', 'Strongest aspects of performance']
    strengthTable = createTable(strengthDf, title ="", colRatio = [1, 5], customTextCols=[0,1], tableTextStyle=subsubheadingStyleL, tableWidth = 0.8, headerColor = uniColor)
    elements.append(strengthTable)

    # for weaknesses now
    elements.append(Spacer(1, 12))
    weaknessDf = studentDf[['Date', weaknesses]]
    weaknessDf = weaknessDf.dropna(subset=[weaknesses])
    weaknessDf.columns = ['Date', 'Areas for improvement']
    weaknessTable = createTable(weaknessDf, title ="", colRatio = [1, 5], customTextCols=[0,1], tableTextStyle=subsubheadingStyleL, tableWidth = 0.8, headerColor = uniColor)
    elements.append(KeepTogether([Paragraph("Areas for Improvement", subheadingStyleL), weaknessTable]))

    doc.build(elements, onFirstPage=getBannerDrawer(f'DCD {cohortname} feedback', studentname))
    
def createCohortReport(df, cohortname):
    folder = f'DCD/{cohortname}'
    thisSiteCols = [col for col in siteCols if col in df.columns]
    print(f"Processing cohort: {cohortname}, Sites columns found: {thisSiteCols}")
    # merge the sites columns into one column called 'Sites Attended'
    display(df[thisSiteCols].head(5))
    df['Sites Attended'] = df[thisSiteCols].apply(lambda x: ', '.join(x.dropna()), axis=1)
    # strip 
    display(df['Sites Attended'])
    df['Sites Attended'] = df['Sites Attended'].str.strip()
    df[colFinished] = df[colFinished].astype(str)
    df = df[df[colFinished] == 'True']
    df["ReadinessLevel"] = (
    df["Readiness to practic"]
    .astype(str)
    .str.extract(r"Level\s*(\d+)", expand=False)
    .astype("Int64")
    )
    for name in df['Student Name'].unique():
        createStudentReport(df, name, folder, cohortname)
        # break # Remove this break to generate reports for all students


createCohortReport(dfPaeds, 'Paeds')
createCohortReport(dfOmed, 'Oral Med')
createCohortReport(dfOrtho, 'Ortho')
createCohortReport(dfPros, 'Pros')
createCohortReport(dfEndo, 'Endo')

Processing cohort: Paeds, Sites columns found: ['Site_4', 'Site_5', 'Site_10', 'Site_11', 'Site_12']

                                 Site_4 Site_5 Site_10 Site_11 Site_12
2  Royal Dental Hospital Melbourne RDHM    NaN     NaN     NaN     NaN
3  Royal Dental Hospital Melbourne RDHM    NaN     NaN     NaN     NaN
4  Royal Dental Hospital Melbourne RDHM    NaN     NaN     NaN     NaN
5                                   NaN    NaN     RCH     NaN     NaN
6  Royal Dental Hospital Melbourne RDHM    NaN     NaN     NaN     NaN

2      Royal Dental Hospital Melbourne RDHM
3      Royal Dental Hospital Melbourne RDHM
4      Royal Dental Hospital Melbourne RDHM
5                                       RCH
6      Royal Dental Hospital Melbourne RDHM
                       ...
284    Royal Dental Hospital Melbourne RDHM
285    Royal Dental Hospital Melbourne RDHM
286                                     RCH
287                 Melbourne Dental Clinic
288    Royal Dental Hospital Melbourne RDHM
Name: Sites Attended, Length: 287, dtype: object

Creating table for
Creating table for
Creating table for
Creating table for

C:\Users\Kunal Patel\AppData\Local\Temp\ipykernel_31512\2890839107.py:234: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ReadinessLevel"] = (

Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Processing cohort: Oral Med, Sites columns found: ['Site_4', 'Site_5']

                                 Site_4                   Site_5
2  Royal Dental Hospital Melbourne RDHM                      NaN
3  Royal Dental Hospital Melbourne RDHM                      NaN
4  Royal Dental Hospital Melbourne RDHM                      NaN
5                                   NaN  Melbourne Dental Clinic
6  Royal Dental Hospital Melbourne RDHM                      NaN

2     Royal Dental Hospital Melbourne RDHM
3     Royal Dental Hospital Melbourne RDHM
4     Royal Dental Hospital Melbourne RDHM
5                  Melbourne Dental Clinic
6     Royal Dental Hospital Melbourne RDHM
7     Royal Dental Hospital Melbourne RDHM
8     Royal Dental Hospital Melbourne RDHM
9     Royal Dental Hospital Melbourne RDHM
10    Royal Dental Hospital Melbourne RDHM
11    Royal Dental Hospital Melbourne RDHM
12    Royal Dental Hospital Melbourne RDHM
13                 Melbourne Dental Clinic
14    Royal Dental Hospital Melbourne RDHM
15    Royal Dental Hospital Melbourne RDHM
16    Royal Dental Hospital Melbourne RDHM
17    Royal Dental Hospital Melbourne RDHM
18    Royal Dental Hospital Melbourne RDHM
Name: Sites Attended, dtype: object

Creating table for
Creating table for
Creating table for
Creating table for
Processing cohort: Ortho, Sites columns found: ['Site_4', 'Site_5']

C:\Users\Kunal Patel\AppData\Local\Temp\ipykernel_31512\2890839107.py:234: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ReadinessLevel"] = (

  Site_4                   Site_5
2    NaN  Melbourne Dental Clinic
3    NaN  Melbourne Dental Clinic
4    NaN  Melbourne Dental Clinic
5    NaN  Melbourne Dental Clinic
6    NaN  Melbourne Dental Clinic

2      Melbourne Dental Clinic
3      Melbourne Dental Clinic
4      Melbourne Dental Clinic
5      Melbourne Dental Clinic
6      Melbourne Dental Clinic
                ...
238    Melbourne Dental Clinic
239    Melbourne Dental Clinic
240    Melbourne Dental Clinic
241    Melbourne Dental Clinic
242    Melbourne Dental Clinic
Name: Sites Attended, Length: 241, dtype: object

Creating table for
Creating table for

C:\Users\Kunal Patel\AppData\Local\Temp\ipykernel_31512\2890839107.py:234: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ReadinessLevel"] = (

Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Processing cohort: Pros, Sites columns found: ['Site_4', 'Site_5']

                                 Site_4 Site_5
2  Royal Dental Hospital Melbourne RDHM    NaN
3  Royal Dental Hospital Melbourne RDHM    NaN
4  Royal Dental Hospital Melbourne RDHM    NaN
5  Royal Dental Hospital Melbourne RDHM    NaN
6  Royal Dental Hospital Melbourne RDHM    NaN

2      Royal Dental Hospital Melbourne RDHM
3      Royal Dental Hospital Melbourne RDHM
4      Royal Dental Hospital Melbourne RDHM
5      Royal Dental Hospital Melbourne RDHM
6      Royal Dental Hospital Melbourne RDHM
                       ...
115    Royal Dental Hospital Melbourne RDHM
116    Royal Dental Hospital Melbourne RDHM
117    Royal Dental Hospital Melbourne RDHM
118    Royal Dental Hospital Melbourne RDHM
119    Royal Dental Hospital Melbourne RDHM
Name: Sites Attended, Length: 118, dtype: object

Creating table for
Creating table for
Creating table for
Creating table for

C:\Users\Kunal Patel\AppData\Local\Temp\ipykernel_31512\2890839107.py:234: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ReadinessLevel"] = (

Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Processing cohort: Endo, Sites columns found: ['Site_4', 'Site_5']

                                 Site_4 Site_5
2  Royal Dental Hospital Melbourne RDHM    NaN
3  Royal Dental Hospital Melbourne RDHM    NaN
4  Royal Dental Hospital Melbourne RDHM    NaN
5  Royal Dental Hospital Melbourne RDHM    NaN
6  Royal Dental Hospital Melbourne RDHM    NaN

2     Royal Dental Hospital Melbourne RDHM
3     Royal Dental Hospital Melbourne RDHM
4     Royal Dental Hospital Melbourne RDHM
5     Royal Dental Hospital Melbourne RDHM
6     Royal Dental Hospital Melbourne RDHM
7     Royal Dental Hospital Melbourne RDHM
8     Royal Dental Hospital Melbourne RDHM
9     Royal Dental Hospital Melbourne RDHM
10    Royal Dental Hospital Melbourne RDHM
11    Royal Dental Hospital Melbourne RDHM
12    Royal Dental Hospital Melbourne RDHM
13    Royal Dental Hospital Melbourne RDHM
14    Royal Dental Hospital Melbourne RDHM
15    Royal Dental Hospital Melbourne RDHM
16    Royal Dental Hospital Melbourne RDHM
17    Royal Dental Hospital Melbourne RDHM
18    Royal Dental Hospital Melbourne RDHM
19    Royal Dental Hospital Melbourne RDHM
20    Royal Dental Hospital Melbourne RDHM
21    Royal Dental Hospital Melbourne RDHM
22    Royal Dental Hospital Melbourne RDHM
23    Royal Dental Hospital Melbourne RDHM
24    Royal Dental Hospital Melbourne RDHM
25    Royal Dental Hospital Melbourne RDHM
26    Royal Dental Hospital Melbourne RDHM
27    Royal Dental Hospital Melbourne RDHM
28    Royal Dental Hospital Melbourne RDHM
29    Royal Dental Hospital Melbourne RDHM
30    Royal Dental Hospital Melbourne RDHM
31    Royal Dental Hospital Melbourne RDHM
32    Royal Dental Hospital Melbourne RDHM
33    Royal Dental Hospital Melbourne RDHM
34    Royal Dental Hospital Melbourne RDHM
35    Royal Dental Hospital Melbourne RDHM
36    Royal Dental Hospital Melbourne RDHM
37    Royal Dental Hospital Melbourne RDHM
38    Royal Dental Hospital Melbourne RDHM
39    Royal Dental Hospital Melbourne RDHM
40    Royal Dental Hospital Melbourne RDHM
Name: Sites Attended, dtype: object

Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for

C:\Users\Kunal Patel\AppData\Local\Temp\ipykernel_31512\2890839107.py:234: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ReadinessLevel"] = (

Creating table for
Creating table for
Creating table for
Creating table for
Creating table for
Creating table for

## Other reports

In [20]:
surveyDict['Case Report'] = 'SV_a3mtKAPnrX8DNvE'
surveyDict['Lit Review'] = 'SV_7W1LelzRLsmPG1E'
surveyDict['Seminar Skills'] = 'SV_6QouNmDXIbUFXOS'
dfCaseReport = Responses().get_survey_responses(survey=surveyDict['Case Report'], verify=None, useLabels=True)
dfLitReview = Responses().get_survey_responses(survey=surveyDict['Lit Review'], verify=None, useLabels=True)
dfSeminarSkills = Responses().get_survey_responses(survey=surveyDict['Seminar Skills'], verify=None, useLabels=True)

In [ ]:
# save them to excel
dfCaseReport.to_excel('DCD/CaseReport.xlsx', index=False)
dfLitReview.to_excel('DCD/LitReview.xlsx', index=False)
dfSeminarSkills.to_excel('DCD/SeminarSkills.xlsx', index=False)